
--POPULATING USER TABLE
INSERT INTO T_FPP_USUARIO(CD_USUARIO, NM_NOME, DT_NASCIMENTO, DS_EMAIL, DS_SENHA) VALUES(1,'Felipe Gandra', TO_DATE('01/03/1984', 'DD/MM/YYYY'), 'fgandraf@gmail.com', '1234');
INSERT INTO T_FPP_USUARIO(CD_USUARIO, NM_NOME, DT_NASCIMENTO, DS_EMAIL, DS_SENHA) VALUES(2,'Henry Thuler', TO_DATE('01/01/1998', 'DD/MM/YYYY'), 'henry@email.com', 'abcd');

--POPULATING CATEGORY TABLE
INSERT INTO T_FPP_CATEGORIA(CD_CATEGORIA, CD_USUARIO, ID_TIPO, DS_DESCRICAO) VALUES(1,1,1,'Aluguel');
INSERT INTO T_FPP_CATEGORIA(CD_CATEGORIA, CD_USUARIO, ID_TIPO, DS_DESCRICAO) VALUES(2,1,2,'Alimentação');

--POPULATING SUBCATEGORY TABLE
INSERT INTO T_FPP_SUBCATEGORIA(CD_SUBCATEGORIA, CD_CATEGORIA, CD_USUARIO, ID_TIPO, DS_DESCRICAO) VALUES(1,2,1,1,'Restaurante');
INSERT INTO T_FPP_SUBCATEGORIA(CD_SUBCATEGORIA, CD_CATEGORIA, CD_USUARIO, ID_TIPO, DS_DESCRICAO) VALUES(2,1,1,2,'Aluguel do apartamento');

--POPULATING INCOME TABLE
INSERT INTO T_FPP_RECEITA(CD_RECEITA, CD_USUARIO, DT_DATA, VL_VALOR, NR_METODO, NM_PAGADOR, DS_DESCRICAO, ST_STATUS, CD_CATEGORIA, CD_SUBCATEGORIA)
VALUES(1,1,TO_DATE('20/10/2023', 'DD/MM/YYYY'), 25.99, 1, 'MEU INQUILINO', 'ALUGUEL DO APTO', 1, 1, 2);

--COMMIT CHANGES
COMMIT





